version: "3.8"
services:
  db:
    build: .
    container_name: db
    restart: always
    image: postgres:16.0-alpine3.18
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DB_NAME -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-server:
    build: .
    container_name: go_server
    command: sh -c "go install && EHealth"
    volumes:
      - .:/code
    ports:
      - $PORT:$PORT
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

volumes:
  postgres-db: